---
name: 'Ansible Galaxy Role Importer'
description: 'Github Action for import your role into Ansible Galaxy.'

inputs:
  api_key:
    description: 'Ansible Galaxy API Key'
    required: true

runs:
  using: 'docker'
  image: 'docker://ghcr.io/hspaans/ansible-galaxy-action:0.1.5'
  env:
    ACTION_API_KEY: ${{ inputs.api_key }}

branding:
  icon: 'book'  
  color: 'gray-dark'
