---
author: 'hspaans'
name: 'Ansible Galaxy Role Importer'
description: 'Github Action for import your role into Ansible Galaxy.'

inputs:
  api_key:
    description: |
      Ansible Galaxy API Key
      Source: https://galaxy.ansible.com/me/preferences
    required: true

runs:
  using: 'composite'
  steps:
    - name: 'Install dependencies'
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install "ansible-core>=2.17.0,<2.18.0"

    - name: 'Install dependencies'
      shell: bash
      run: entrypoint.sh
      env:
        ACTION_API_KEY: ${{ inputs.api_key }}

branding:
  icon: 'book'
  color: 'gray-dark'
