#!/bin/bash
set -e

command_string="ansible-galaxy role import"

if [ -n "$action_api_key" ]
then
	command_string="$command_string --api-key $action_api_key ${GITHUB_REPOSITORY%/*} ${GITHUB_REPOSITORY#*/}"
fi

echo "Command: $command_string"
eval "$command_string"
