---
name: CI

on:
  push:
    branches:
      - master
      - v*
    tags:
      - v*
  pull_request:
    # The branches below must be a subset of the branches above
    branches:
      - master

permissions:
  contents: read

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master

      - name: Set up Python
        uses: actions/setup-python@v6

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pymarkdownlnt yamllint

      - name: Lint with yamllint
        run: |
          yamllint . --format github

      - name: Lint with pymarkdownlnt
        run: |
          pymarkdownlnt scan `git ls-files '*.md' ':!:*TEMPLATE/*md'`
