---
name: Close stale issues and pull-requests

on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    permissions:
      issues: write
      pull-requests: write
    name: GitHub Action Stale
    uses: hspaans/.github/.github/workflows/reusable-stale.yml@master
