---
name: "Close Stale Issues"
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3.0.12
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

          days-before-stale: 60
          days-before-close: 7

          operations-per-run: 30

          remove-stale-when-updated: true

          stale-issue-label: no-issue-activity
          exempt-issue-labels: work-in-progress
          stale-issue-message: >-
            This issue has been marked 'stale' due to lack of recent activity. The issue will be closed in another 7 days.
          close-issue-message: >-
            This issue has been closed due to inactivity. If you feel this is in error, please reopen the issue or file a new issue with the relevant details.

          stale-pr-label: no-pr-activity
          exempt-pr-labels: awaiting-approval
          stale-pr-message: >-
            This pull request has been marked 'stale' due to lack of recent activity. The PR will be closed in another 7 days.
          close-pr-message: >-
            This pull request has been closed due to inactivity. Please reopen the pull request or file a new PR with the relevant details.
